apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: vaults.gcp.vaultongke.crossplane.io
spec:
  group: gcp.vaultongke.crossplane.io
  names:
    kind: Vaults
    plural: vaults
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              operators:
                type: object
                description: Configuration for operators.
                properties:
                  prometheus:
                    type: object
                    description: Configuration for the Vault.
                    properties:
                      version:
                        type: string
                        description: Vault version to run.
              providerConfigRef:
                type: object
                description: "A reference to the ProviderConfig of the cluster that Vault should
                be deployed to."
                properties:
                  name:
                    type: string
                    description: "Name of the Kubernetes provider configuration.
                      This will typically be the name of the cluster with a
                      five character suffix appended."
                required:
                - name
            required:
            - providerConfigRef
