apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-ref-multi-vault
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/platform-ref-multi-vault
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      The reference platform for running a highly available Vault. Currently, it only supports GCP.
    meta.crossplane.io/readme: |
      This reference platform Configuration for Vault defines necessary compositions
      to run a highly available Vault. Currently, this configuration only supports GCP.

      It provides a platform API to provision fully configured GKE clusters,
      with secure networking, and a highly available Vault backed by GCS bucket and
      configured to auto unseal with Cloud KMS using GCP workload identity -- all
      composed using cloud service primitives from the [Crossplane GCP
      Provider](https://marketplace.upbound.io/providers/crossplane/provider-gcp). App
      deployments can securely connect to the infrastructure they need using
      secrets distributed directly to the app namespace.

      [Quickstart
      Guide](https://github.com/upbound/platform-ref-multi-vault/#quick-start)

      To learn more checkout the [GitHub
      repo](https://github.com/upbound/platform-ref-multi-vault/) that you can copy and
      customize to meet the exact needs of your organization!
spec:
  crossplane:
    version: ">=v1.6.0-0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane/provider-gcp
      version: ">=v0.19.0-0"
    - provider: xpkg.upbound.io/crossplane/provider-helm
      version: ">=v0.9.0-0"
